server:
  port: 8089

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
spring:
  application:
    name: spring-cloud-provider-01
info: 
  app.name: wangk-microservicecloud
  company.name: www.wangk.com
  artifactId: @project.artifactId@
  version: @project.version@

management:
  health:
    db:
      enabled: false
    solr:
      enabled: false 
    elasticsearch: 
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      sensitive: false
  endpoint:
    health:
      show-details: ALWAYS
